apiVersion: batch/v1
kind: Job
metadata:
    name: {{ .Release.Name }}-abathur-control
    namespace: {{ .Release.Namespace }}
    labels:
        component: control
        instance: p{{ .Values.gitlab.pipeline }}-abathur-control
spec:
  template:
    metadata:
      labels:
        component: control
        instance: p{{ .Values.gitlab.pipeline }}-abathur-control
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.abathurControl.ip }}\"]"
    spec:
      {{- with .Values.abathurControl }}
      containers:
        - name: abathur-control
          image: {{ .image.repository }}:{{ .image.tag }}
          imagePullPolicy: {{ .image.imagePullPolicy }}
          resources:
            limits:
              cpu: {{ .resources.cpu }}
              memory: {{ .resources.memory }}
            requests:
              cpu: {{ .resources.cpu }}
              memory: {{ .resources.memory }}          
          {{- with .securityContext | default $.Values.defaults.securityContext }}
          securityContext:
              {{- toYaml . | nindent 14 }}
          {{- end }}
      {{- end }}
          volumeMounts:
            - name: {{ .Release.Name }}-properties
              mountPath: /usr/src/control/props
          env:
            - name: LOG_TYPE
              value: {{ .Values.logger.logType }}
            - name: LOG_LVL
              value: {{ .Values.logger.logLevel }}
            - name: FUNC_SCENARIO
              value: {{ .Values.abathurControl.funcScenario }}
      volumes:
        - name: {{ .Release.Name }}-properties
          configMap:
            name: {{ .Release.Name }}-properties
      serviceAccountName: {{ .Release.Name }}-abathur
      restartPolicy: {{ .Values.abathurControl.restartPolicy }}
  backoffLimit: 0