apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-properties
  namespace: {{ .Release.Namespace }}
  labels:
    component: properties
    instance: p{{ .Values.gitlab.pipeline }}-abathur-control
data:
  config.properties: |
    IMAGE_PULL_SECRETS={{ .Values.abathurControl.image.imagePullSecrets }}
    HBF_MIGRATION_REPOSITORY={{ .Values.hbfMigration.image.repository }}
    HBF_MIGRATION_TAG={{ .Values.hbfMigration.image.tag }}
    HBF_SERVER_REPOSITORY={{ .Values.hbfServer.image.repository }}
    HBF_SERVER_TAG={{ .Values.hbfServer.image.tag }}
    HBF_SERVER_DB_LOGIN={{ .Values.hbfServer.database.login }}
    HBF_SERVER_DB_PWD={{ .Values.hbfServer.database.pwd }}
    HBF_SERVER_DB_PORT={{ .Values.hbfServer.database.port }}
    HBF_SERVER_DB_NAME={{ .Values.hbfServer.database.name }}
    S2S_HBF_SERVER_IP={{ .Values.hbfServer.scenario.func.s2s.ip }}
    S2S_HBF_SERVER_PORT={{ .Values.hbfServer.scenario.func.s2s.port  | toString }}
    S2F_HBF_SERVER_IP={{ .Values.hbfServer.scenario.func.s2f.ip }}
    S2F_HBF_SERVER_PORT={{ .Values.hbfServer.scenario.func.s2f.port  | toString }}
    CANGE_IP_HBF_SERVER_IP={{ .Values.hbfServer.scenario.func.changeIP.ip }}
    CANGE_IP_HBF_SERVER_PORT={{ .Values.hbfServer.scenario.func.changeIP.port  | toString }}
    ICMP_HBF_SERVER_IP={{  .Values.hbfServer.scenario.func.icmp.ip }}
    ICMP_HBF_SERVER_PORT={{ .Values.hbfServer.scenario.func.icmp.port | toString }}
    A_HBF_SERVER_IP={{ .Values.hbfServer.scenario.api.ip }}
    A_HBF_SERVER_PORT={{ .Values.hbfServer.scenario.api.port | toString }}
    S2C_IE_HBF_SERVER_IP={{ .Values.hbfServer.scenario.func.s2cIE.ip }}
    S2C_IE_HBF_SERVER_PORT={{ .Values.hbfServer.scenario.func.s2cIE.port | toString }}
    S2S_IE_HBF_SERVER_IP={{ .Values.hbfServer.scenario.func.s2sIE.ip }}
    S2S_IE_HBF_SERVER_PORT={{ .Values.hbfServer.scenario.func.s2sIE.port | toString }}
    HBF_CLIENT_REPOSITORY={{ .Values.hbfClient.image.repository }}
    HBF_CLIENT_TAG={{ .Values.hbfClient.image.tag }}
    ABA_CLIENT_REPOSITORY={{ .Values.abathurClient.image.repository }}
    ABA_CLIENT_TAG={{ .Values.abathurClient.image.tag }}
    ABA_SERVER_REPOSITORY={{ .Values.abathurServer.image.repository }}
    ABA_SERVER_TAG={{ .Values.abathurServer.image.tag }}
    PIPELINE_ID={{ .Values.gitlab.pipeline | toString }}
    JOB_ID={{ .Values.gitlab.job | default (include "control.random" .) | toString }}
    CI_SOURCE_BRANCH_NAME={{ $.Values.gitlab.src_branch }}
    COMMIT={{ $.Values.gitlab.commit }}
    HBF_TAG={{ $.Values.hbfServer.image.tag }}
    HBF_REPORTER_PROTOCOL={{ .Values.hbfReporter.protocol }}
    HBF_REPORTER_HOST={{ .Values.hbfReporter.host }}
    HBF_REPORTER_PORT={{ .Values.hbfReporter.port | toString }}
    API_REPORTER_PROTOCOL={{ .Values.apiReporter.protocol }}
    API_REPORTER_HOST={{ .Values.apiReporter.host }}
    API_REPORTER_PORT={{ .Values.apiReporter.port | toString }}
    NAMESPACE={{ .Release.Namespace }}
    ABA_CONTROL_IP={{ .Values.abathurControl.ip }}
    ABA_CONTROL_PORT={{ .Values.abathurControl.port | toString }}
    ABA_PROXY_PORT={{ .Values.abathurControl.proxyPort | toString }}
    ABA_PROXY_PROTOCOL={{ .Values.abathurControl.proxyProtocol }}
    IS_DESTROY_AFTER={{ .Values.abathurControl.destroy }}
    TG_TOKEN={{ .Values.telegram.token }}
    TG_GROUP_ID={{ .Values.telegram.groupId }}
    API_TEST_REPOSITORY={{ .Values.apiTests.image.repository }}
    API_TEST_TAG={{ .Values.apiTests.image.tag }}
    API_TEST_IP={{ .Values.apiTests.ip }}
    ABA_SERVER_CPU={{ .Values.abathurServer.resources.cpu }}
    ABA_SERVER_MEM={{ .Values.abathurServer.resources.memory }}
    ABA_CLIENT_CPU={{ .Values.abathurClient.resources.cpu }}
    ABA_CLIENT_MEM={{ .Values.abathurClient.resources.memory }}
    HBF_SERVER_CPU={{ .Values.hbfServer.resources.cpu }}
    HBF_SERVER_MEM={{ .Values.hbfServer.resources.memory }}
    HBF_CLIENT_CPU={{ .Values.hbfClient.resources.cpu }}
    HBF_CLIENT_MEM={{ .Values.hbfClient.resources.memory }}
    HBF_MIGRATION_CPU={{ .Values.hbfMigration.resources.cpu }}
    HBF_MIGRATION_MEM={{ .Values.hbfMigration.resources.memory }}
    API_TEST_CPU={{ .Values.apiTests.resources.cpu }}
    API_TEST_MEM={{ .Values.apiTests.resources.memory }}
    DNS_IP={{ .Values.hbfClient.dns.ip }}
    DNS_PROTOCOL={{ .Values.hbfClient.dns.protocol }}
    DNS_PORT={{ .Values.hbfClient.dns.port }}
    LOG_TYPE={{ .Values.logger.logType }}
    LOG_LVL={{ .Values.logger.logLevel }}