apiVersion: v1
kind: ServiceAccount
metadata:
  name: abathur
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    name: abathur
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Pod
metadata:
  name: abathur-control
  namespace: default
  labels:
    app.kubernetes.io/name: abathur-control
spec:
  containers:
    - name: control
      image: abathur_control
      env:
        - name: HBF_SERVER_VERSION
          value: '1.1.3'
        - name: HBF_CLIENT_VERSION
          value: '1.1.3'
        - name: PIPELINE_ID
          value: '123456'
      ports:
        - containerPort: 80
          name: test
      securityContext:
        privileged: true
      imagePullPolicy: Never
  serviceAccountName: abathur
  restartPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: abathur-control
spec:
  selector:
    app.kubernetes.io/name: abathur-control
  ports:
  - port: 8080
    targetPort: test

---

apiVersion: v1
kind: Pod
metadata:
  name: "report-server"
  labels:
    name: "report-server"
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.150.0.230\"]"
spec:
  containers:
    - name: report-server
      image: abathur_report_server
      imagePullPolicy: Never
  restartPolicy: Never