apiVersion: v1
kind: Pod
metadata:
  name: my-pod-0
  namespace: default
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.150.0.220\"]"
  labels:
    name: nginx
spec:
  securityContext:
   sysctls:
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.ip_local_reserved_ports
      value: "40000-55000"

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

    - name: server
      image: hbftest_server
      imagePullPolicy: Never

    - name: client
      image: hbftest_client
      imagePullPolicy: Never
    
    - name: hbf-client
      image: fraima/hbf-client:1.1.3
      securityContext:
        privileged: true
      volumeMounts:
        - name: hbf-client
          mountPath: /app/hack/configs/to-nft.yaml
          subPath: conf.yaml
      command: [ "./bin/to-nft", "-config", "/app/hack/configs/to-nft.yaml" ]
  restartPolicy: Never

  volumes:
    - name: nginx
      configMap:
        name: nginx
    - name: hbf-client
      configMap:
        name: hbf-client

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
  namespace: default
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.150.0.221\"]"
  labels:
    name: nginx
spec:
  securityContext:
   sysctls:
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.ip_local_reserved_ports
      value: "40000-55000"

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

    - name: server
      image: hbftest_server
      imagePullPolicy: Never

    - name: client
      image: hbftest_client
      imagePullPolicy: Never

    - name: hbf-client
      image: fraima/hbf-client:1.1.3
      securityContext:
        privileged: true
      volumeMounts:
        - name: hbf-client
          mountPath: /app/hack/configs/to-nft.yaml
          subPath: conf.yaml
      command: [ "./bin/to-nft", "-config", "/app/hack/configs/to-nft.yaml" ]
      
  restartPolicy: Never

  volumes:
  - name: nginx
    configMap:
      name: nginx
  - name: hbf-client
    configMap:
      name: hbf-client

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
  namespace: default
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.150.0.222\"]"
  labels:
    name: nginx
spec:
  securityContext:
   sysctls:
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.ip_local_reserved_ports
      value: "40000-55000"

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

    - name: server
      image: hbftest_server
      imagePullPolicy: Never

    - name: client
      image: hbftest_client
      imagePullPolicy: Never

    - name: hbf-client
      image: fraima/hbf-client:1.1.3
      securityContext:
        privileged: true
      volumeMounts:
        - name: hbf-client
          mountPath: /app/hack/configs/to-nft.yaml
          subPath: conf.yaml
      command: [ "./bin/to-nft", "-config", "/app/hack/configs/to-nft.yaml" ]      
      
  restartPolicy: Never

  volumes:
  - name: nginx
    configMap:
      name: nginx
  - name: hbf-client
    configMap:
      name: hbf-client

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-3
  namespace: default
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.150.0.223\"]"
  labels:
    name: nginx
spec:
  securityContext:
   sysctls:
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.ip_local_reserved_ports
      value: "40000-55000"

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

    - name: server
      image: hbftest_server
      imagePullPolicy: Never

    - name: client
      image: hbftest_client
      imagePullPolicy: Never

    - name: hbf-client
      image: fraima/hbf-client:1.1.3
      securityContext:
        privileged: true
      volumeMounts:
        - name: hbf-client
          mountPath: /app/hack/configs/to-nft.yaml
          subPath: conf.yaml      
      command: [ "./bin/to-nft", "-config", "/app/hack/configs/to-nft.yaml" ]
      
  restartPolicy: Never

  volumes:
  - name: nginx
    configMap:
      name: nginx
  - name: hbf-client
    configMap:
      name: hbf-client

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-4
  namespace: default
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.150.0.224\"]"
  labels:
    name: nginx
spec:
  securityContext:
   sysctls:
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.ip_local_reserved_ports
      value: "40000-55000"

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

    - name: server
      image: hbftest_server
      imagePullPolicy: Never

    - name: client
      image: hbftest_client
      imagePullPolicy: Never

    - name: hbf-client
      image: fraima/hbf-client:1.1.3
      securityContext:
        privileged: true
      volumeMounts:
        - name: hbf-client
          mountPath: /app/hack/configs/to-nft.yaml
          subPath: conf.yaml
      command: [ "./bin/to-nft", "-config", "/app/hack/configs/to-nft.yaml" ]
      
  restartPolicy: Never

  volumes:
  - name: nginx
    configMap:
      name: nginx
  - name: hbf-client
    configMap:
      name: hbf-client

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-5
  namespace: default
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.150.0.225\"]"
  labels:
    name: nginx
spec:
  securityContext:
   sysctls:
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.ip_local_reserved_ports
      value: "40000-55000"

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

    - name: server
      image: hbftest_server
      imagePullPolicy: Never

    - name: client
      image: hbftest_client
      imagePullPolicy: Never

    - name: hbf-client
      image: fraima/hbf-client:1.1.3
      securityContext:
        privileged: true
      volumeMounts:
        - name: hbf-client
          mountPath: /app/hack/configs/to-nft.yaml
          subPath: conf.yaml
      command: [ "./bin/to-nft", "-config", "/app/hack/configs/to-nft.yaml" ]
      
  restartPolicy: Never

  volumes:
  - name: nginx
    configMap:
      name: nginx
  - name: hbf-client
    configMap:
      name: hbf-client

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-6
  namespace: default
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.150.0.226\"]"
  labels:
    name: nginx
spec:
  securityContext:
   sysctls:
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.ip_local_reserved_ports
      value: "40000-55000"

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

    - name: server
      image: hbftest_server
      imagePullPolicy: Never

    - name: client
      image: hbftest_client
      imagePullPolicy: Never

    - name: hbf-client
      image: fraima/hbf-client:1.1.3
      securityContext:
        privileged: true
      volumeMounts:
        - name: hbf-client
          mountPath: /app/hack/configs/to-nft.yaml
          subPath: conf.yaml
      command: [ "./bin/to-nft", "-config", "/app/hack/configs/to-nft.yaml" ]
      
  restartPolicy: Never

  volumes:
  - name: nginx
    configMap:
      name: nginx
  - name: hbf-client
    configMap:
      name: hbf-client

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-7
  namespace: default
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.150.0.227\"]"
  labels:
    name: nginx
spec:
  securityContext:
   sysctls:
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.ip_local_reserved_ports
      value: "40000-55000"

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

    - name: server
      image: hbftest_server
      imagePullPolicy: Never

    - name: client
      image: hbftest_client
      imagePullPolicy: Never

    - name: hbf-client
      image: fraima/hbf-client:1.1.3
      securityContext:
        privileged: true
      volumeMounts:
        - name: hbf-client
          mountPath: /app/hack/configs/to-nft.yaml
          subPath: conf.yaml
      command: [ "./bin/to-nft", "-config", "/app/hack/configs/to-nft.yaml" ]
      
  restartPolicy: Never

  volumes:
  - name: nginx
    configMap:
      name: nginx
  - name: hbf-client
    configMap:
      name: hbf-client

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-8
  namespace: default
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.150.0.228\"]"
  labels:
    name: nginx
spec:
  securityContext:
   sysctls:
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.ip_local_reserved_ports
      value: "40000-55000"

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

    - name: server
      image: hbftest_server
      imagePullPolicy: Never

    - name: client
      image: hbftest_client
      imagePullPolicy: Never

    - name: hbf-client
      image: fraima/hbf-client:1.1.3
      securityContext:
        privileged: true
      volumeMounts:
        - name: hbf-client
          mountPath: /app/hack/configs/to-nft.yaml
          subPath: conf.yaml
      command: [ "./bin/to-nft", "-config", "/app/hack/configs/to-nft.yaml" ]
      
  restartPolicy: Never

  volumes:
  - name: nginx
    configMap:
      name: nginx
  - name: hbf-client
    configMap:
      name: hbf-client

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-9
  namespace: default
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.150.0.229\"]"
  labels:
    name: nginx
spec:
  securityContext:
   sysctls:
    - name: net.ipv4.tcp_tw_reuse
      value: "1"
    - name: net.ipv4.ip_local_reserved_ports
      value: "40000-55000"

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

    - name: server
      image: hbftest_server
      imagePullPolicy: Never

    - name: client
      image: hbftest_client
      imagePullPolicy: Never

    - name: hbf-client
      image: fraima/hbf-client:1.1.3
      securityContext:
        privileged: true
      volumeMounts:
        - name: hbf-client
          mountPath: /app/hack/configs/to-nft.yaml
          subPath: conf.yaml
      command: [ "./bin/to-nft", "-config", "/app/hack/configs/to-nft.yaml" ]
      
  restartPolicy: Never

  volumes:
  - name: nginx
    configMap:
      name: nginx
  - name: hbf-client
    configMap:
      name: hbf-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-server
  labels:
    app: report-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-server
  template:
    metadata:
      labels:
        app: report-server
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"10.150.0.230\"]"
    spec:
      containers:
        - name: report-server
          image: hbftest_report_server
          imagePullPolicy: Never
        
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:   
  nginx.conf: |
    user www-data;        
    worker_processes auto;
    pid /run/nginx.pid;
    include /etc/nginx/modules-enabled/*.conf;

    events {
            worker_connections 30000;
            # multi_accept on;
    }

    http {
            log_format custom '$remote_addr:$remote_port src: $http_src_ip:$http_src_port / dst: $http_dst_ip:$http_dst_port / protocol: $http_protocol';

            server {
                listen 50000-55000;
                http2 on;
                
                location / {
                    grpc_pass grpc://127.0.0.1:9091;
                    grpc_set_header dst-port $http_dst_port;
                } 
            }

            server {
                listen 80;
                http2 on;

                location / {
                    set $port "";

                    if ($http_src_port != "") {
                      set $port :$http_src_port;
                    } 

                    grpc_bind $http_src_ip$port;
                    grpc_pass grpc://$http_dst_ip:$http_dst_port;
                    grpc_set_header dst-port $http_dst_port;
                }
            }

            sendfile on;
            tcp_nopush on;
            types_hash_max_size 2048;

            # include /etc/nginx/mime.types;
            default_type application/octet-stream;


            # ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
            # ssl_prefer_server_ciphers on;

            access_log /var/log/nginx/access.log custom;
            error_log /var/log/nginx/error.log;


            gzip on;

            include /etc/nginx/conf.d/*.conf;
            include /etc/nginx/sites-enabled/*;
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hbf-client
data:   
  conf.yaml: |
    ---
    graceful-shutdown: 10s
    logger:
      level: INFO

    extapi:
      svc:
        def-daial-duration: 10s
        sgroups:
          dial-duration: 3s
          address: tcp://193.32.219.99:9000
          check-sync-status: 5s