apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: new-pool-one
  namespace: default
spec:
  blockSize: 32
  cidr: 10.150.0.0/16
  ipipMode: CrossSubnet
  natOutgoing: true
  disabled: false
  nodeSelector: all()