abathurControl:
  image:
    imagePullPolicy: Never
    repository: abathur_control
    tag: latest
    # repository: harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-control
    # tag: feature-delete-job-554eaa78
  ip: 29.64.0.231
  ports:
    addressPort: 80
    addressPortAlias: aba-port
  # securityContext:
  #   privileged: true
  restartPolicy: Never
  destroy: false


abathurClient:
  image:
    repository: abathur_client
    tag: latest
    # repository: harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-client
    # tag: feature-delete-job-554eaa78

abathurServer:
  image:
    repository: abathur_server
    tag: latest
    # repository: harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-server
    # tag: feature-delete-job-554eaa78

hbfServer:
  image:
    repository: harbor.wildberries.ru/swarm/swarm/swarm/sgroups/sgroups
    # tag: v1-0-2-947f9db4
    tag: feature-swarm-47-d4548df1

hbfClient:
  image:
    repository: harbor.wildberries.ru/swarm/swarm/swarm/sgroups/to-nft
    # tag: v1-0-2-947f9db4
    tag: feature-swarm-47-d4548df1

hbfReporter:
  protocol: http
  host: 172.25.143.81
  port: 9000

# hbfReporter:
#   protocol: http
#   host: 10.36.38.132
#   port: 80

gitlab:
  random: 6
  pipeline: 123456
  # job: ""
  src_branch: from
  dst_branch: to
  commit: 34er3r323

defaults:
  securityContext: {}