abathurControl:
  image:
    imagePullPolicy: Never
    repository: abathur_control
    tag: latest
  ip: 29.64.0.231
  port: 9091
  ports:
    addressPort: 80
    addressPortAlias: aba-port
  resources:
    cpu: 300m
    memory: 500Mi
  # securityContext:
  #   privileged: true
  restartPolicy: Never
  destroy: true
  scenario: 99

abathurClient:
  image:
    repository: abathur_client
    tag: latest
  resources:
    cpu: 100m
    memory: 500Mi

abathurServer:
  image:
    repository: abathur_server
    tag: latest
  resources:
    cpu: 100m
    memory: 500Mi

hbfServer:
  image:
    repository: harbor.wildberries.ru/swarm/swarm/swarm/sgroups/sgroups
    tag: v1-0-3-rc5-339b0961
  resources:
    cpu: 100m
    memory: 100Mi
  scenario:
    func:
      ip: 29.64.0.232
      port: 9006
    api:
      ip: 29.64.0.233
      port: 9006

hbfClient:
  image:
    repository: harbor.wildberries.ru/swarm/swarm/swarm/sgroups/to-nft
    tag: v1-0-3-rc5-339b0961
  resources:
    cpu: 100m
    memory:  100Mi
  dns:
    ip: 10.96.0.10
    port: 53
    protocol: udp

apiTests:
  image:
    repository: "hbf_api_tests"
    tag: "latest"
  ip: 29.64.0.255
  resources:
    cpu: 300m
    memory: 300Mi

# LOCAL
hbfReporter:
  protocol: http
  host: 172.25.143.81
  port: 9000

# WB
# hbfReporter:
#   protocol: http
#   host: 10.36.36.186
#   port: 80

# LOCAL
apiReporter:
  protocol: http
  host: 172.25.143.81
  port: 9001

# WB
# apiReporter:
#   protocol: http
#   host: 10.36.37.165
#   port: 80

gitlab:
  random: 6
  pipeline: 878789
  # job: ""
  src_branch: from
  dst_branch: to
  commit: 34er3r323

telegram:
  token: 5996680756:AAGHDMu5WnkaVioGJbesVJMv8irooQvfL7g
  groupId: "-1001959123261"

defaults:
  securityContext: {}