abathurControl:
  image:
    imagePullPolicy: Never
    repository: abathur_control
    tag: latest
    # repository: harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-control
    # tag: feature-delete-job-554eaa78
  ip: 29.64.0.231
  port: 9091
  ports:
    addressPort: 80
    addressPortAlias: aba-port
  # securityContext:
  #   privileged: true
  restartPolicy: Never
  destroy: true
  scenario: 99

abathurClient:
  image:
    repository: abathur_client
    tag: latest
    # repository: harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-client
    # tag: feature-delete-job-554eaa78

abathurServer:
  image:
    repository: abathur_server
    tag: latest
    # repository: harbor.wildberries.ru/swarm/swarm/testops/abathur/aba-server
    # tag: feature-delete-job-554eaa78

hbfServer:
  image:
    repository: harbor.wildberries.ru/swarm/swarm/swarm/sgroups/sgroups
    tag: v1-0-3-rc5-339b0961
  scenario:
    func:
      ip: 29.64.0.232
      port: 9006
    api:
      ip: 29.64.0.233
      port: 9006

hbfClient:
  image:
    repository: harbor.wildberries.ru/swarm/swarm/swarm/sgroups/to-nft
    tag: v1-0-3-rc5-339b0961

apiTests:
  image:
    repository: "hbf_api_tests"
    tag: "latest"
  ip: 29.64.0.255

# LOCAL
# hbfReporter:
#   protocol: http
#   host: 172.25.143.81
#   port: 9000

# WB
hbfReporter:
  protocol: http
  host: 10.36.36.186
  port: 80

# LOCAL
# apiReporter:
#   protocol: http
#   host: 172.25.143.81
#   port: 9001

# WB
apiReporter:
  protocol: http
  host: 10.36.37.165
  port: 80

gitlab:
  random: 6
  pipeline: 878789
  # job: ""
  src_branch: from
  dst_branch: to
  commit: 34er3r323

telegram:
  token: 5996680756:AAGHDMu5WnkaVioGJbesVJMv8irooQvfL7g
  groupId: "-1001959123261"

defaults:
  securityContext: {}