abathurControl:
  image:
    imagePullPolicy: Never
    repository: abathur_control
    tag: latest
  ip: 29.64.0.231
  ports:
    addressPort: 80
    addressPortAlias: aba-port
  securityContext:
    privileged: true
  restartPolicy: Never

abathurClient:
  image:
    repository: abathur_client
    tag: latest

abathurServer:
  image:
    repository: abathur_server
    tag: latest

hbfServer:
  image:
    repository: harbor.wildberries.ru/swarm/swarm/swarm/sgroups/sgroups
    tag: v1-0-2-947f9db4

hbfClient:
  image:
    repository: harbor.wildberries.ru/swarm/swarm/swarm/sgroups/to-nft
    tag: v1-0-2-947f9db4

hbfReporter:
  protocol: http
  host: 172.25.143.81
  port: 9000

# hbfReporter:
#   protocol: http
#   host: 10.36.38.132
#   port: 80

gitlab:
  random: 6
  pipeline: 123456
  # job: ""
  src_branch: from
  dst_branch: to
  commit: 34er3r323

defaults:
  securityContext: {}